/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SeedanceRouteImport } from './routes/seedance'
import { Route as IndexRouteImport } from './routes/index'

const SeedanceRoute = SeedanceRouteImport.update({
  id: '/seedance',
  path: '/seedance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/seedance': typeof SeedanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/seedance': typeof SeedanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/seedance': typeof SeedanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/seedance'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/seedance'
  id: '__root__' | '/' | '/seedance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeedanceRoute: typeof SeedanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seedance': {
      id: '/seedance'
      path: '/seedance'
      fullPath: '/seedance'
      preLoaderRoute: typeof SeedanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeedanceRoute: SeedanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
