import { describe, expect, it } from 'vitest'
import { EventType } from '@tanstack/ai/client'
import {
  GENERATION_EVENTS,
  parseGenerationResumeSnapshot,
  updateGenerationResumeSnapshot,
} from '../src/generation-types'
import type { PersistedArtifactRef, StreamChunk } from '@tanstack/ai/client'
import type { GenerationResumeSnapshot } from '../src/generation-types'

const artifactRef: PersistedArtifactRef = {
  role: 'output',
  artifactId: 'artifact-1',
  threadId: 'thread-1',
  runId: 'run-1',
  name: 'image.png',
  mimeType: 'image/png',
  size: 1234,
  createdAt: '2026-07-06T00:00:00.000Z',
  source: {
    activity: 'image',
    path: 'thread-1/run-1/image.png',
    provider: 'test',
    model: 'image-model',
    mediaType: 'image',
  },
}

function reduceChunks(
  chunks: ReadonlyArray<StreamChunk>,
  initial?: GenerationResumeSnapshot,
): GenerationResumeSnapshot {
  let snapshot = initial
  for (const chunk of chunks) {
    snapshot = updateGenerationResumeSnapshot(snapshot, chunk)
  }
  if (!snapshot) {
    throw new Error('Expected at least one generation event')
  }
  return snapshot
}

describe('generation resume state reducer', () => {
  it('tracks thread and run from persisted generation events', () => {
    const snapshot = reduceChunks([
      {
        type: EventType.RUN_STARTED,
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 1,
      },
      {
        type: EventType.CUSTOM,
        name: GENERATION_EVENTS.PROGRESS,
        value: { progress: 50, message: 'Halfway' },
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 2,
      },
    ])

    expect(snapshot).toMatchObject({
      resumeState: {
        threadId: 'thread-1',
        runId: 'run-1',
      },
      status: 'running',
      lastEvent: {
        type: EventType.CUSTOM,
        name: GENERATION_EVENTS.PROGRESS,
      },
    })
  })

  it('stores generation artifacts as persisted refs only', () => {
    const snapshot = reduceChunks([
      {
        type: EventType.CUSTOM,
        name: GENERATION_EVENTS.ARTIFACTS,
        value: [
          artifactRef,
          {
            b64Json: 'raw-media-bytes',
            url: 'data:image/png;base64,raw-media-bytes',
          },
        ],
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 1,
      },
    ])

    expect(snapshot.pendingArtifacts).toEqual([artifactRef])
    expect(JSON.stringify(snapshot)).not.toContain('raw-media-bytes')
    expect(snapshot.activity).toBe('image')
  })

  it('sanitizes artifact refs before storing them in resume snapshots', () => {
    const unsafeArtifactRef = {
      ...artifactRef,
      sourceUrl: 'data:image/png;base64,raw-artifact-bytes',
      b64Json: 'raw-artifact-bytes',
      blob: new Blob(['raw-artifact-bytes']),
      url: `https://example.com/${'x'.repeat(4096)}`,
      source: {
        ...artifactRef.source,
        extraRawField: 'raw-artifact-bytes',
      },
    }

    const snapshot = reduceChunks([
      {
        type: EventType.CUSTOM,
        name: GENERATION_EVENTS.ARTIFACTS,
        value: [unsafeArtifactRef],
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 1,
      },
      {
        type: EventType.CUSTOM,
        name: GENERATION_EVENTS.RESULT,
        value: {
          id: 'result-1',
          artifacts: [unsafeArtifactRef],
        },
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 2,
      },
    ])

    expect(snapshot.pendingArtifacts).toEqual([artifactRef])
    expect(snapshot.result?.artifacts).toEqual([artifactRef])
    expect(JSON.stringify(snapshot)).not.toContain('raw-artifact-bytes')
    expect(JSON.stringify(snapshot)).not.toContain('b64Json')
    expect(JSON.stringify(snapshot)).not.toContain('extraRawField')
  })

  it('stores terminal result metadata without raw generated bytes', () => {
    const snapshot = reduceChunks([
      {
        type: EventType.CUSTOM,
        name: GENERATION_EVENTS.RESULT,
        value: {
          id: 'result-1',
          model: 'image-model',
          images: [
            {
              b64Json: 'raw-image-bytes',
              url: 'data:image/png;base64,raw-image-bytes',
              revisedPrompt: 'clean prompt',
            },
          ],
          artifacts: [artifactRef],
        },
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 2,
      },
      {
        type: EventType.RUN_FINISHED,
        threadId: 'thread-1',
        runId: 'run-1',
        finishReason: 'stop',
        timestamp: 3,
      },
    ])

    expect(snapshot.resumeState).toBeNull()
    expect(snapshot.status).toBe('complete')
    expect(snapshot.result).toMatchObject({
      id: 'result-1',
      model: 'image-model',
      artifacts: [artifactRef],
    })
    expect(JSON.stringify(snapshot)).not.toContain('raw-image-bytes')
    expect(JSON.stringify(snapshot)).not.toContain('b64Json')
  })

  it('keeps a durable artifact sourceUrl and strips non-durable or oversized ones', () => {
    const durableUrl = 'https://cdn.example.com/artifacts/image.png'
    const durable = reduceChunks([
      {
        type: EventType.CUSTOM,
        name: GENERATION_EVENTS.ARTIFACTS,
        value: [{ ...artifactRef, sourceUrl: durableUrl }],
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 1,
      },
    ])
    expect(durable.pendingArtifacts?.[0]?.sourceUrl).toBe(durableUrl)

    const unsafeUrls = [
      'data:image/png;base64,raw-image-bytes',
      'blob:https://example.com/raw-image-bytes',
      `https://example.com/${'x'.repeat(4096)}`,
      'not a url',
    ]
    for (const sourceUrl of unsafeUrls) {
      const snapshot = reduceChunks([
        {
          type: EventType.CUSTOM,
          name: GENERATION_EVENTS.ARTIFACTS,
          value: [{ ...artifactRef, sourceUrl }],
          threadId: 'thread-1',
          runId: 'run-1',
          timestamp: 1,
        },
      ])
      expect(snapshot.pendingArtifacts).toEqual([artifactRef])
      expect(snapshot.pendingArtifacts?.[0]).not.toHaveProperty('sourceUrl')
    }
  })

  it('clears resume state and stores lightweight error metadata on terminal errors', () => {
    const snapshot = reduceChunks([
      {
        type: EventType.RUN_STARTED,
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 1,
      },
      {
        type: EventType.RUN_ERROR,
        threadId: 'thread-1',
        runId: 'run-1',
        message: 'Generation failed',
        code: 'provider_error',
        error: { message: 'legacy message' },
        timestamp: 2,
      },
    ])

    expect(snapshot).toMatchObject({
      resumeState: null,
      status: 'error',
      error: {
        message: 'Generation failed',
        code: 'provider_error',
      },
    })
  })

  it('captures the video job id from video:job:created before any result arrives', () => {
    const snapshot = reduceChunks([
      {
        type: EventType.RUN_STARTED,
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 1,
      },
      {
        type: EventType.CUSTOM,
        name: GENERATION_EVENTS.VIDEO_JOB_CREATED,
        value: { jobId: 'job-42' },
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 2,
      },
    ])

    expect(snapshot.status).toBe('running')
    expect(snapshot.result?.providerJobId).toBe('job-42')
  })

  it('merges an initial seed and lets later run events update it', () => {
    const seed: GenerationResumeSnapshot = {
      resumeState: null,
      status: 'error',
      error: { message: 'previous failure' },
      pendingArtifacts: [artifactRef],
    }

    const midRun = reduceChunks(
      [
        {
          type: EventType.CUSTOM,
          name: GENERATION_EVENTS.PROGRESS,
          value: { progress: 10 },
          threadId: 'thread-1',
          runId: 'run-2',
          timestamp: 1,
        },
      ],
      seed,
    )
    // Without a RUN_STARTED boundary the seed's fields are carried forward.
    expect(midRun.resumeState).toEqual({ threadId: 'thread-1', runId: 'run-2' })
    expect(midRun.error).toEqual({ message: 'previous failure' })
    expect(midRun.pendingArtifacts).toEqual([artifactRef])
  })

  it('drops stale error, result, and artifacts when a new run starts', () => {
    const seed: GenerationResumeSnapshot = {
      resumeState: null,
      status: 'error',
      error: { message: 'previous failure' },
      result: { id: 'old-result' },
      pendingArtifacts: [artifactRef],
    }

    const snapshot = reduceChunks(
      [
        {
          type: EventType.RUN_STARTED,
          threadId: 'thread-1',
          runId: 'run-2',
          timestamp: 1,
        },
      ],
      seed,
    )

    expect(snapshot.status).toBe('running')
    expect(snapshot.resumeState).toEqual({
      threadId: 'thread-1',
      runId: 'run-2',
    })
    expect(snapshot.error).toBeUndefined()
    expect(snapshot.result).toBeUndefined()
    expect(snapshot.pendingArtifacts).toBeUndefined()
  })
})

describe('parseGenerationResumeSnapshot', () => {
  it('round-trips a reducer-produced snapshot through JSON, dropping lastEvent', () => {
    const produced = reduceChunks([
      {
        type: EventType.RUN_STARTED,
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 1,
      },
      {
        type: EventType.CUSTOM,
        name: GENERATION_EVENTS.RESULT,
        value: {
          id: 'result-1',
          model: 'image-model',
          artifacts: [artifactRef],
        },
        threadId: 'thread-1',
        runId: 'run-1',
        timestamp: 2,
      },
      {
        type: EventType.RUN_FINISHED,
        threadId: 'thread-1',
        runId: 'run-1',
        finishReason: 'stop',
        timestamp: 3,
      },
    ])

    const parsed = parseGenerationResumeSnapshot(
      JSON.parse(JSON.stringify(produced)),
    )
    expect(parsed).toBeDefined()
    expect(parsed?.status).toBe('complete')
    expect(parsed?.resumeState).toBeNull()
    expect(parsed?.result).toEqual(produced.result)
    expect(parsed?.lastEvent).toBeUndefined()
  })

  it('rejects garbage, invalid statuses, malformed resume state, and future schema versions', () => {
    expect(parseGenerationResumeSnapshot(undefined)).toBeUndefined()
    expect(parseGenerationResumeSnapshot('running')).toBeUndefined()
    expect(parseGenerationResumeSnapshot({})).toBeUndefined()
    expect(
      parseGenerationResumeSnapshot({ resumeState: null, status: 'paused' }),
    ).toBeUndefined()
    expect(
      parseGenerationResumeSnapshot({
        resumeState: { threadId: 'thread-1' },
        status: 'running',
      }),
    ).toBeUndefined()
    expect(
      parseGenerationResumeSnapshot({
        schemaVersion: 2,
        resumeState: null,
        status: 'idle',
      }),
    ).toBeUndefined()
  })

  it('strips unknown fields and re-validates artifact refs from storage', () => {
    const parsed = parseGenerationResumeSnapshot({
      resumeState: { threadId: 'thread-1', runId: 'run-1' },
      status: 'running',
      pendingArtifacts: [artifactRef, { b64Json: 'raw-bytes' }],
      error: { message: 'boom', code: 'E1', extra: 'dropped' },
      injected: 'dropped',
    })

    expect(parsed).toBeDefined()
    expect(parsed?.pendingArtifacts).toEqual([artifactRef])
    expect(parsed?.error).toEqual({ message: 'boom', code: 'E1' })
    expect(JSON.stringify(parsed)).not.toContain('raw-bytes')
    expect(JSON.stringify(parsed)).not.toContain('dropped')
  })
})
