export { useChat } from './use-chat'
export { useMcpAppBridge } from './use-mcp-app-bridge'
export type { UseMcpAppBridgeOptions } from './use-mcp-app-bridge'
export type {
  UseChatOptions,
  UseChatReturn,
  UIMessage,
  ChatRequestBody,
  QueuedMessage,
  SendMessageOptions,
  WhenBusy,
  QueueConfig,
  QueueStrategy,
  QueueOption,
} from './types'

export {
  fetchServerSentEvents,
  localStoragePersistence,
  sessionStoragePersistence,
  indexedDBPersistence,
  StorageUnavailableError,
  type ChatClientPersistence,
  type ChatPersistedState,
  type ChatPersistenceOption,
  type ChatStorageAdapter,
  type WebStoragePersistenceOptions,
  type IndexedDBPersistenceOptions,
  fetchHttpStream,
  xhrServerSentEvents,
  xhrHttpStream,
  stream,
  rpcStream,
  createChatClientOptions,
  createMcpAppBridge,
  type McpAppBridge,
  type CreateMcpAppBridgeOptions,
  type ConnectionAdapter,
  type ConnectConnectionAdapter,
  type SubscribeConnectionAdapter,
  type RunAgentInputContext,
  type FetchConnectionOptions,
  type XhrConnectionOptions,
  type InferChatMessages,
} from '@tanstack/ai-client'
