/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRunRouteImport } from './routes/api.run'
import { Route as ApiRunCancelRouteImport } from './routes/api.run.cancel'
import { Route as ApiRunActiveRouteImport } from './routes/api.run.active'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunRoute = ApiRunRouteImport.update({
  id: '/api/run',
  path: '/api/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunCancelRoute = ApiRunCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => ApiRunRoute,
} as any)
const ApiRunActiveRoute = ApiRunActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => ApiRunRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/run': typeof ApiRunRouteWithChildren
  '/api/run/active': typeof ApiRunActiveRoute
  '/api/run/cancel': typeof ApiRunCancelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/run': typeof ApiRunRouteWithChildren
  '/api/run/active': typeof ApiRunActiveRoute
  '/api/run/cancel': typeof ApiRunCancelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/run': typeof ApiRunRouteWithChildren
  '/api/run/active': typeof ApiRunActiveRoute
  '/api/run/cancel': typeof ApiRunCancelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/run' | '/api/run/active' | '/api/run/cancel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/run' | '/api/run/active' | '/api/run/cancel'
  id: '__root__' | '/' | '/api/run' | '/api/run/active' | '/api/run/cancel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRunRoute: typeof ApiRunRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run': {
      id: '/api/run'
      path: '/api/run'
      fullPath: '/api/run'
      preLoaderRoute: typeof ApiRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run/cancel': {
      id: '/api/run/cancel'
      path: '/cancel'
      fullPath: '/api/run/cancel'
      preLoaderRoute: typeof ApiRunCancelRouteImport
      parentRoute: typeof ApiRunRoute
    }
    '/api/run/active': {
      id: '/api/run/active'
      path: '/active'
      fullPath: '/api/run/active'
      preLoaderRoute: typeof ApiRunActiveRouteImport
      parentRoute: typeof ApiRunRoute
    }
  }
}

interface ApiRunRouteChildren {
  ApiRunActiveRoute: typeof ApiRunActiveRoute
  ApiRunCancelRoute: typeof ApiRunCancelRoute
}

const ApiRunRouteChildren: ApiRunRouteChildren = {
  ApiRunActiveRoute: ApiRunActiveRoute,
  ApiRunCancelRoute: ApiRunCancelRoute,
}

const ApiRunRouteWithChildren =
  ApiRunRoute._addFileChildren(ApiRunRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRunRoute: ApiRunRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
