import { useState } from 'react'
import type { ReactNode } from 'react'
import { createFileRoute } from '@tanstack/react-router'
import {
  FileAudio,
  FileText,
  Image,
  Mic,
  Music,
  Play,
  RotateCcw,
  Video,
} from 'lucide-react'
import {
  useGenerateAudio,
  useGenerateImage,
  useGenerateSpeech,
  useGenerateVideo,
  useSummarize,
  useTranscription,
} from '@tanstack/ai-react'
import { fetchServerSentEvents } from '@tanstack/ai-client'

/**
 * Every generation surface, persisted, on one page — the manual-verification
 * harness for generation persistence.
 *
 * The five MEDIA activities (image, audio, speech, transcription, video) are
 * **server-driven**: `persistence: true` + a `connection`. The browser caches
 * nothing; the server records each run and copies the generated bytes into its
 * own store (see `../lib/generation-server-store` and the `/api/generate/*`
 * routes). On mount the hook issues a `GET …?threadId=…`, answered by
 * `reconstructGeneration`, so a full reload restores the result — and if the
 * run is still in flight, the hook rejoins its stream and finishes it in place.
 *
 * `summarize` produces text rather than media, so it stores no artifacts, but it
 * persists the same way: the summary text rides on the run record, and the
 * mount-time hydration repaints it.
 *
 * Each hook has a stable `threadId` — the scope the run is filed under and the
 * key hydration looks it up by, so it must not change across reloads.
 */

function PersistentGenerationPage() {
  const [imagePrompt, setImagePrompt] = useState('a lighthouse at dusk')
  const [audioPrompt, setAudioPrompt] = useState('a calm lofi beat')
  const [speechText, setSpeechText] = useState(
    'Persistence keeps this generation across a reload.',
  )
  const [summaryText, setSummaryText] = useState(SAMPLE_TEXT)
  const [videoPrompt, setVideoPrompt] = useState('a paper plane over a city')

  // --- Media: server-driven (persistence: true + connection) ---------------

  const image = useGenerateImage({
    threadId: 'persistent-generation:image',
    connection: fetchServerSentEvents('/api/generate/image'),
    persistence: true,
  })

  const audio = useGenerateAudio({
    threadId: 'persistent-generation:audio',
    connection: fetchServerSentEvents('/api/generate/audio'),
    // Fal-backed (FAL_KEY): gemini-lyria needs a Gemini key this example's
    // .env doesn't ship. Swap the provider if you have a different key set.
    body: { provider: 'fal-audio', model: 'fal-ai/elevenlabs/music' },
    persistence: true,
  })

  const speech = useGenerateSpeech({
    threadId: 'persistent-generation:speech',
    connection: fetchServerSentEvents('/api/generate/speech'),
    body: { provider: 'openai' },
    persistence: true,
  })

  const transcription = useTranscription({
    threadId: 'persistent-generation:transcription',
    connection: fetchServerSentEvents('/api/transcribe'),
    body: { provider: 'openai' },
    persistence: true,
  })

  const video = useGenerateVideo({
    threadId: 'persistent-generation:video',
    connection: fetchServerSentEvents('/api/generate/video'),
    persistence: true,
  })

  // --- Text: client-driven (summary text lives in the snapshot) ------------

  const summarize = useSummarize({
    threadId: 'persistent-generation:summarize',
    connection: fetchServerSentEvents('/api/summarize'),
    body: { model: 'gpt-5.5' },
    persistence: true,
  })

  const handleTranscribe = async (
    e: React.ChangeEvent<HTMLInputElement>,
  ): Promise<void> => {
    const file = e.target.files?.[0]
    if (!file) return
    const buffer = await file.arrayBuffer()
    const base64 = btoa(
      new Uint8Array(buffer).reduce((s, b) => s + String.fromCharCode(b), ''),
    )
    await transcription.generate({
      audio: `data:${file.type};base64,${base64}`,
      language: 'en',
    })
    e.target.value = ''
  }

  return (
    <main className="min-h-screen bg-gray-950 text-white">
      <div className="mx-auto flex w-full max-w-7xl flex-col gap-6 px-6 py-8">
        <section className="space-y-2 border-b border-gray-800 pb-6">
          <p className="text-xs font-semibold uppercase tracking-wider text-cyan-300">
            Generation persistence
          </p>
          <h2 className="text-3xl font-semibold tracking-tight">
            Persistent Generation
          </h2>
          <p className="max-w-3xl text-sm leading-6 text-gray-400">
            Every generation surface, persisted. Start any run and reload the
            page: a run still in flight reconnects and finishes; a finished run
            restores from the server. Summarize restores from localStorage.
          </p>
        </section>

        <section className="grid gap-4 xl:grid-cols-2">
          <Card
            title="useGenerateImage"
            mode="server"
            icon={Image}
            status={image.status}
            isLoading={image.isLoading}
            error={image.error}
            onGenerate={() => void image.generate({ prompt: imagePrompt })}
            onReset={image.reset}
          >
            <input
              value={imagePrompt}
              onChange={(e) => setImagePrompt(e.target.value)}
              disabled={image.isLoading}
              className="w-full rounded-md border border-gray-800 bg-gray-950 px-3 py-2 text-sm outline-none focus:border-cyan-500"
            />
            <div className="grid gap-3 sm:grid-cols-2">
              {image.result?.images.map((img, i) => (
                <img
                  key={i}
                  data-testid="persistent-image"
                  src={img.url ?? `data:image/png;base64,${img.b64Json}`}
                  alt={img.revisedPrompt ?? `image ${i + 1}`}
                  className="aspect-video w-full rounded-md border border-gray-800 object-cover"
                />
              ))}
            </div>
          </Card>

          <Card
            title="useGenerateVideo"
            mode="server"
            icon={Video}
            status={video.status}
            isLoading={video.isLoading}
            error={video.error}
            onGenerate={() => void video.generate({ prompt: videoPrompt })}
            onReset={video.reset}
            onStop={video.stop}
          >
            <input
              value={videoPrompt}
              onChange={(e) => setVideoPrompt(e.target.value)}
              disabled={video.isLoading}
              className="w-full rounded-md border border-gray-800 bg-gray-950 px-3 py-2 text-sm outline-none focus:border-cyan-500"
            />
            <div className="grid gap-2 text-xs text-gray-400 sm:grid-cols-3">
              <span>job {video.jobId ?? 'none'}</span>
              <span>status {video.videoStatus?.status ?? 'idle'}</span>
              <span>
                progress{' '}
                {video.videoStatus?.progress == null
                  ? '0%'
                  : `${video.videoStatus.progress}%`}
              </span>
            </div>
            {video.result?.url && (
              <video
                data-testid="persistent-video"
                src={video.result.url}
                controls
                className="aspect-video w-full rounded-md border border-gray-800 bg-black"
              />
            )}
          </Card>

          <Card
            title="useGenerateAudio"
            mode="server"
            icon={Music}
            status={audio.status}
            isLoading={audio.isLoading}
            error={audio.error}
            onGenerate={() => void audio.generate({ prompt: audioPrompt })}
            onReset={audio.reset}
          >
            <input
              value={audioPrompt}
              onChange={(e) => setAudioPrompt(e.target.value)}
              disabled={audio.isLoading}
              className="w-full rounded-md border border-gray-800 bg-gray-950 px-3 py-2 text-sm outline-none focus:border-cyan-500"
            />
            {audio.result?.audio.url && (
              <audio
                data-testid="persistent-audio"
                src={audio.result.audio.url}
                controls
                className="w-full"
              />
            )}
          </Card>

          <Card
            title="useGenerateSpeech"
            mode="server"
            icon={FileAudio}
            status={speech.status}
            isLoading={speech.isLoading}
            error={speech.error}
            onGenerate={() => void speech.generate({ text: speechText })}
            onReset={speech.reset}
          >
            <textarea
              value={speechText}
              onChange={(e) => setSpeechText(e.target.value)}
              rows={3}
              disabled={speech.isLoading}
              className="w-full rounded-md border border-gray-800 bg-gray-950 px-3 py-2 text-sm outline-none focus:border-cyan-500"
            />
            {(() => {
              // Prefer the durable serve URL (present live and after restore);
              // fall back to the live base64 the provider streamed. On a reload
              // only the URL survives — the bytes were never cached client-side.
              // In the fallback `audio` is always raw base64 (the live TTS
              // result), so build a data URL directly rather than sniffing.
              const durable = speech.result?.artifacts?.find(
                (a) => a.role === 'output' && a.url,
              )?.url
              const src =
                durable ??
                (speech.result?.audio
                  ? `data:${speech.result.contentType ?? 'audio/mpeg'};base64,${speech.result.audio}`
                  : undefined)
              return src ? (
                <audio
                  data-testid="persistent-speech"
                  src={src}
                  controls
                  className="w-full"
                />
              ) : null
            })()}
          </Card>

          <Card
            title="useTranscription"
            mode="server"
            icon={Mic}
            status={transcription.status}
            isLoading={transcription.isLoading}
            error={transcription.error}
            onReset={transcription.reset}
          >
            <input
              type="file"
              accept="audio/*"
              onChange={(e) => void handleTranscribe(e)}
              disabled={transcription.isLoading}
              className="w-full text-xs text-gray-400 file:mr-3 file:rounded-md file:border-0 file:bg-cyan-600 file:px-3 file:py-1.5 file:text-white"
            />
            <p
              data-testid="persistent-transcription"
              className="rounded-md border border-gray-800 bg-gray-950 px-3 py-2 text-sm leading-6 text-gray-200"
            >
              {transcription.result?.text ??
                'Upload an audio file to transcribe.'}
            </p>
          </Card>

          <Card
            title="useSummarize"
            mode="client"
            icon={FileText}
            status={summarize.status}
            isLoading={summarize.isLoading}
            error={summarize.error}
            onGenerate={() =>
              void summarize.generate({ text: summaryText, style: 'concise' })
            }
            onReset={summarize.reset}
          >
            <textarea
              value={summaryText}
              onChange={(e) => setSummaryText(e.target.value)}
              rows={4}
              disabled={summarize.isLoading}
              className="w-full rounded-md border border-gray-800 bg-gray-950 px-3 py-2 text-sm outline-none focus:border-cyan-500"
            />
            <p
              data-testid="persistent-summary"
              className="rounded-md border border-gray-800 bg-gray-950 px-3 py-2 text-sm leading-6 text-gray-200"
            >
              {summarize.result?.summary ?? 'No summary yet.'}
            </p>
          </Card>
        </section>
      </div>
    </main>
  )
}

function Card({
  title,
  mode,
  icon: Icon,
  status,
  isLoading,
  error,
  onGenerate,
  onReset,
  onStop,
  children,
}: {
  title: string
  mode: 'server' | 'client'
  icon: typeof Image
  status: string
  isLoading: boolean
  error?: Error
  onGenerate?: () => void
  onReset: () => void
  onStop?: () => void
  children: ReactNode
}) {
  return (
    <article className="flex min-h-72 flex-col gap-4 rounded-lg border border-gray-800 bg-gray-900 p-4">
      <header className="flex items-start justify-between gap-4">
        <div className="flex min-w-0 items-center gap-3">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-md bg-cyan-500/10 text-cyan-300">
            <Icon size={20} />
          </div>
          <div className="min-w-0">
            <h3 className="truncate text-base font-semibold text-white">
              {title}
            </h3>
            <p className="truncate font-mono text-xs text-gray-500">
              {mode === 'server'
                ? 'persistence: true (server-driven)'
                : 'localStorage (client-driven)'}
            </p>
          </div>
        </div>
        <span
          data-testid={`status-${title}`}
          className={`shrink-0 rounded-md px-2 py-1 font-mono text-xs ${
            isLoading
              ? 'bg-cyan-500/15 text-cyan-200'
              : status === 'error'
                ? 'bg-red-500/15 text-red-200'
                : status === 'success'
                  ? 'bg-emerald-500/15 text-emerald-200'
                  : 'bg-gray-800 text-gray-300'
          }`}
        >
          {status}
        </span>
      </header>

      <div className="flex flex-wrap gap-2">
        {onGenerate && (
          <button
            type="button"
            onClick={onGenerate}
            disabled={isLoading}
            className="inline-flex items-center gap-2 rounded-md bg-cyan-600 px-3 py-2 text-xs font-semibold text-white transition-colors hover:bg-cyan-500 disabled:bg-gray-800 disabled:text-gray-500"
          >
            <Play size={14} />
            Generate
          </button>
        )}
        {onStop && isLoading && (
          <button
            type="button"
            onClick={onStop}
            className="inline-flex items-center gap-2 rounded-md border border-red-500/40 px-3 py-2 text-xs font-semibold text-red-200 transition-colors hover:bg-red-500/10"
          >
            Stop
          </button>
        )}
        <button
          type="button"
          onClick={onReset}
          className="inline-flex items-center gap-2 rounded-md border border-gray-700 px-3 py-2 text-xs font-semibold text-gray-200 transition-colors hover:bg-gray-800"
        >
          <RotateCcw size={14} />
          Reset
        </button>
      </div>

      {error && (
        <p className="rounded-md border border-red-500/20 bg-red-500/10 px-3 py-2 text-sm text-red-200">
          {error.message}
        </p>
      )}

      <div className="flex flex-1 flex-col gap-3">{children}</div>
    </article>
  )
}

const SAMPLE_TEXT = `Artificial intelligence has moved from research labs into everyday products at remarkable speed. Large language models now write code, translate languages, and reason about complex problems. This shift raises questions about reliability, bias, and the cost of training, even as the tools become more useful across healthcare, education, and creative work.`

export const Route = createFileRoute('/generations/persistent-generation')({
  component: PersistentGenerationPage,
})
